### PR TITLE
[ADD] trackingCode Init-Check

### PR DESCRIPTION
**Pull request by xerc**
ref. https://developer.matomo.org/guides/tracking-javascript-guide
fyi/ prefere not to use `||`

### CODE REVIEW

**Review by brotkrueml — COMMENTED** [review]
Please elaborate what do you want to achieve with it and what problem it solves.

Also I cannot find the given snippet in the linked docs.

**Comment by xerc** [comment]
1. https://stackoverflow.com/questions/62758236/ ; `window._paq` needs to exist
2. because i wrote the `if`-block myself to prevent usage of `||` and var-chaining

**Comment by brotkrueml** [comment]
> 1. https://stackoverflow.com/questions/62758236/ ; `window._paq` needs to exist
> 2. because i wrote the `if`-block myself to prevent usage of `||` and var-chaining

Then this should be enough: `var _paq = window._paq = window._paq || [];` 

But as `_paq` is defined always in global scope, `_paq` is then equal with `window._paq` AFAIK?

And why the `Array` thingy? That would mean, that someone defined `_paq` with a string, for example, then it is overridden by your code suggestion. So either the application (which expects the string which you override with the array check) or Matomo (which expects an array and gets a string) will fail. So your suggestion does nothing better. Or do I miss something?

**Comment by xerc** [comment]
> > 1. https://stackoverflow.com/questions/62758236/ ; `window._paq` needs to exist
> > 2. because i wrote the `if`-block myself to prevent usage of `||` and var-chaining
> 
> Then this should be enough: `var _paq = window._paq = window._paq || [];`

i've checked the v4 source @ https://github.com/matomo-org/matomo/blob/4.x-dev/js/piwik.js
`_paq` is used directly (without checking `window.`)

> But as `_paq` is defined always in global scope, `_paq` is then equal with `window._paq` AFAIK?

only if not defined as `var` ; https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/scope-closures/ch4.md#globals-shadowing-globals

> And why the `Array` thingy? That would mean, that someone defined `_paq` with a string, for example, then it is overridden by your code suggestion. 

true ; because Matomo expects Array|Object

> So either the application (which expects the string which you override with the array check) or Matomo (which expects an array and gets a string) will fail. So your suggestion does nothing better. Or do I miss something?

if there is just String within `_paq` it will get overwritten and Matomo gets Array corrrectly

**Comment by brotkrueml** [comment]
Okay, but why deviate from the recommendation of Matomo which has this in their prepared script snippet:
`var _paq = window._paq = window._paq || [];`
Should this then not be an issue at their side?
Sorry, but I just want to understand.

**Comment by xerc** [comment]
i would define this version as outdated ; they do not access `window._paq`
and if `_paq='';` was declared before this script `.push` will not work nor tracking

**Comment by brotkrueml** [comment]
> i would define this version as outdated ; they do not access `window._paq` and if `_paq='';` was declared before this script `.push` will not work nor tracking

Thinking about this loud: When they change their code to access `window._paq` your code would run, as it is defined in global scope (which is `window`).

But: When running the array check on console (on a site which has no Matomo script embedded) I'm getting this error:

    _paq instanceof Array
    VM138:1 Uncaught ReferenceError: _paq is not defined
        at <anonymous>:1:1
    (anonymous) @ VM138:1

**Comment by xerc** [comment]
yea; looks like they are not sure either ..
https://github.com/matomo-org/matomo/search?o=desc&q=window._paq&s=&type=issues
but Array is definitely required ; if `window._paq = 'text'` it will fail anyway with theyr spec.

**Comment by brotkrueml** [comment]
> yea; looks like they are not sure either .. https://github.com/matomo-org/matomo/search?o=desc&q=window._paq&s=&type=issues but Array is definitely required ; if `window._paq = 'text'` it will fail anyway with theyr spec.

Okay, to summerize:
- When `_paq` is defined "outside" the embedded Matomo script (not as an Array), this would clash with Matomo, as that non-array is not compatible with the push function. So to speak, `_paq` is a reserved variable name when using Matomo.
- With your solution at least Matomo will run.
- But then: Some application set this `_paq` and would mostly not run as expected as this variable is now an array.
- We have this snippet from Matomo which runs mostly out-of-the-box (as I heard no complaint from the users of this extension).
- As Matomo promotes the current method with the `||` variant, it works reliable for most cases.
- The current implementation may cause problems when using multiple Matomo instances on one page. But this extension does not cover that case (and mostly will not cover it in the future). I will provide a note in the documentation to hint to this limitation.

So my suggestion: Put the array check variant behind a feature flag which can be enabled on purpose. The default is to not activate the flag and deliver the "old" variant. I don't like to roll out the change in a minor release (and a major (breaking) release is not in sight for now). In a major release we can then enable it by default and/or remove the old variant with `||` altogether.

The feature flag can be available in the site configuration, as it can then be enabled on a site basis (like the other settings of this extension).

What do you think?

**Comment by xerc** [comment]
> * As Matomo promotes the current method with the `||` variant, it works reliable for most cases.

will breake if `_paq` is not Array (first three point in your list)
also google uses this "check" may nobody sets it outside ?!

> * The current implementation may cause problems when using multiple Matomo instances on one page. But this extension does not cover that case (and mostly will not cover it in the future). I will provide a note in the documentation to hint to this limitation.

thx

> So my suggestion: Put the array check variant behind a feature flag which can be enabled on purpose. The default is to not activate the flag and deliver the "old" variant. I don't like to roll out the change in a minor release (and a major (breaking) release is not in sight for now). In a major release we can then enable it by default and/or remove the old variant with `||` altogether.

this version is definitely more reliable but i am with your proposal (not to break major)

**Comment by brotkrueml** [comment]
I rethought it and a feature flag is not worth it. So I will add it to main directly and release it with the next version.

**Pull request merged**
